In [1]:
import numpy as np
from sklearn.datasets import load_breast_cancer
import csv

data = load_breast_cancer()
d = data['data']
print(d.shape)
print(data['feature_names'])

list(data.target_names)



pd = np.zeros_like(d, int)

for i in range(d.shape[1]):
  min = np.min(d[:, i])
  max = np.max(d[:, i]) - min
  mean = np.mean(d[:, i])
  pd[:, i] = d[:, i] >= mean
  #pd[:, i] = np.ceil(100*(d[:, i]-min)/max)
print(pd, np.max(pd, 0), np.min(pd, 0))

print(pd.shape, data['target'].shape)

nt = np.concatenate((data['target'].reshape(-1, 1), np.zeros((140, 1))), 0)

#q = np.concatenate((pd, nt), 1)

q = np.concatenate((pd, data['target'].reshape(-1, 1)), 1)


print(q.shape)

# Write the document vectors to csv files
def writeToCsv(outPath, corpus):
    f = open(outPath, "a", newline='')
    w = csv.writer(f, dialect='excel')
    for x in corpus:
        w.writerow(x)
    f.close()

np.random.seed(20)
np.random.shuffle(q)

train = q[:470, :]
test = q[470:, :]

writeToCsv("train1.csv", train)
writeToCsv("test1.csv", test)


np.random.seed(21)
np.random.shuffle(q)

train = q[:470, :]
test = q[470:, :]

writeToCsv("train2.csv", train)
writeToCsv("test2.csv", test)

np.random.seed(22)
np.random.shuffle(q)

train = q[:470, :]
test = q[470:, :]

writeToCsv("train3.csv", train)
writeToCsv("test3.csv", test)


(569, 30)
['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
[[1 0 1 ... 1 1 1]
 [1 0 1 ... 1 0 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 0 0]
 [1 1 1 ... 1 1 1]
 [0 1 0 ... 0 0 0]] [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
(569, 30) (569,)
(569, 31)


In [2]:
import numpy as np
import math
import csv
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()
d = data['data']
print(d.shape)
print(data['feature_names'])

list(data.target_names)




r = np.random.choice(30, d.shape[0])

for i in range(d.shape[0]):
  if np.random.rand() > 0.5:
    d[i, r[i]] = None

id = np.zeros((d.shape[0], d.shape[1]*2))

for i in range(d.shape[1]):
  mn = 0
  count = 0
  for j in range(d.shape[0]):
    if not math.isnan(d[j, i]) :
      count += 1
      mn = mn + d[j, i]
      id[j, i] = d[j, i]
  
  mn = mn/count
  
  for j in range(d.shape[0]):
    if math.isnan(d[j, i]):
      id[j, i] = mn
      id[j, 30+i] = 1

pd = id.copy()

for i in range(d.shape[1]):
  min = np.min(id[:, i])
  max = np.max(id[:, i]) - min
  mean = np.mean(id[:, i])  
  pd[:, i] = id[:, i] >= mean
  #pd[:, i] = np.ceil(100*(id[:, i]-min)/max)
print(pd, np.max(pd, 0), np.min(pd, 0))

print(pd.shape, data['target'].shape)

nt = np.concatenate((data['target'].reshape(-1, 1), np.zeros((140, 1))), 0)

#q = np.concatenate((pd, nt), 1)

q = np.concatenate((pd, data['target'].reshape(-1, 1)), 1)



print(q.shape)

# Write the document vectors to csv files
def writeToCsv(outPath, corpus):
    f = open(outPath, "a", newline='')
    w = csv.writer(f, dialect='excel')
    for x in corpus:
        w.writerow(x)
    f.close()

np.random.seed(20)
np.random.shuffle(q)

train = q[:470, :]
test = q[470:, :]

writeToCsv("train1.csv", train)
writeToCsv("test1.csv", test)


np.random.seed(21)
np.random.shuffle(q)

train = q[:470, :]
test = q[470:, :]

writeToCsv("train2.csv", train)
writeToCsv("test2.csv", test)

np.random.seed(22)
np.random.shuffle(q)

train = q[:470, :]
test = q[470:, :]

writeToCsv("train3.csv", train)
writeToCsv("test3.csv", test)

(569, 30)
['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
[[1. 0. 1. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 